package synapticloop.linode.api.response;

// - - - - thoughtfully generated by synapticloop linode-api - - - - 
//     with the use of synapticloop templar templating language
//               (java-create-api-test.templar)

import java.util.HashMap;
import java.util.Map;

import synapticloop.linode.LinodeApiRequest;
import synapticloop.linode.exception.ApiException;

import static org.junit.Assert.*;

import org.json.JSONException;
import org.json.JSONObject;
import org.junit.Before;
import org.junit.Test;

import synapticloop.linode.exception.ApiException;


/**
 * This is a generated test class for the Stackscript api calls, this was 
 * automatically generated from the linode api documentation - which can be 
 * found here:
 * <a href="http://www.linode.com/api/stackscript">http://www.linode.com/api/stackscript</a>
 * 
 * @author synapticloop
 */

public class StackscriptGeneratedResponseTest {

	@Test
	public void testStackscript_create() throws JSONException, ApiException {

		new StackscriptResponse(new JSONObject("{" + 
				"   ERRORARRAY: [ ]," + 
				"   DATA: {" + 
				"      StackScriptID: 3" + 
				"   }," + 
				"   ACTION: \"stackscript.create\"" + 
				"}"));

	}


	@Test
	public void testStackscript_delete() throws JSONException, ApiException {

		new StackscriptResponse(new JSONObject("{" + 
				"   ERRORARRAY: [ ]," + 
				"   DATA: {" + 
				"      StackScriptID: 3" + 
				"   }," + 
				"   ACTION: \"stackscript.delete\"" + 
				"}"));

	}


	@Test
	public void testStackscriptList_list() throws JSONException, ApiException {

		new StackscriptListResponse(new JSONObject("{" + 
				"   ERRORARRAY: [ ]," + 
				"   DATA: [" + 
				"      {" + 
				"         SCRIPT: \"#!/bin/bash" + 
				"                  # this is the content of the first StackScript\"," + 
				"         DESCRIPTION: \"\"," + 
				"         DISTRIBUTIONIDLIST: \"77,78\"," + 
				"         LABEL: \"StackScript001\"," + 
				"         DEPLOYMENTSTOTAL: 1," + 
				"         LATESTREV: 1," + 
				"         CREATE_DT: \"2012-05-22 16:35:42.0\"," + 
				"         DEPLOYMENTSACTIVE: 1," + 
				"         STACKSCRIPTID: 1," + 
				"         REV_NOTE: \"Initial import\"," + 
				"         REV_DT: \"2012-05-22 16:35:42.0\"," + 
				"         ISPUBLIC: 1," + 
				"         USERID: 91886" + 
				"      }," + 
				"      {" + 
				"         SCRIPT: \"#!/bin/bash" + 
				"                  # this is the content of the other script\"," + 
				"         DESCRIPTION: \"\"," + 
				"         DISTRIBUTIONIDLIST: \"77,78\"," + 
				"         LABEL: \"StackScript002\"," + 
				"         DEPLOYMENTSTOTAL: 0," + 
				"         LATESTREV: 2," + 
				"         CREATE_DT: \"2012-05-22 17:12:48.0\"," + 
				"         DEPLOYMENTSACTIVE: 0," + 
				"         STACKSCRIPTID: 2," + 
				"         REV_NOTE: \"Initial import\"," + 
				"         REV_DT: \"2012-05-22 17:12:48.0\"," + 
				"         ISPUBLIC: 1," + 
				"         USERID: 91886" + 
				"      }" + 
				"   ]," + 
				"   ACTION: \"stackscript.list\"" + 
				"}"));

	}


	@Test
	public void testStackscript_update() throws JSONException, ApiException {

		new StackscriptResponse(new JSONObject("{" + 
				"   ERRORARRAY: [ ]," + 
				"   DATA: {" + 
				"      StackScriptID: 3718" + 
				"   }," + 
				"   ACTION: \"stackscript.update\"" + 
				"}"));

	}

};