package synapticloop.linode.api.response;

// - - - - thoughtfully generated by synapticloop linode-api - - - - 
//     with the use of synapticloop templar templating language
//               (java-create-api-test.templar)

import java.util.HashMap;
import java.util.Map;

import synapticloop.linode.LinodeApiRequest;
import synapticloop.linode.exception.ApiException;

import static org.junit.Assert.*;

import org.json.JSONException;
import org.json.JSONObject;
import org.junit.Before;
import org.junit.Test;

import synapticloop.linode.exception.ApiException;


/**
 * This is a generated test class for the User api calls, this was 
 * automatically generated from the linode api documentation - which can be 
 * found here:
 * <a href="http://www.linode.com/api/account">http://www.linode.com/api/account</a>
 * 
 * @author synapticloop
 */

public class UserGeneratedResponseTest {

	@Test
	public void testUserGetApiKey_getapikey() throws JSONException, ApiException {

		new UserGetApiKeyResponse(new JSONObject("{" + 
				"   \"ERRORARRAY\":[]," + 
				"   \"ACTION\":\"user.getAPIKey\"," + 
				"   \"DATA\":{" + 
				"      \"USERNAME\":\"chris\"," + 
				"      \"API_KEY\":\"aNW3ydF53LpVftU9s50e0reFEwy0piwGhwaLKAj4okRZ\"" + 
				"   }" + 
				"}"));

	}

};