package synapticloop.linode.api;

// - - - - thoughtfully generated by synapticloop linode-api - - - - 
//     with the use of synapticloop templar templating language
//               (java-create-api.templar)

import java.util.HashMap;
import java.util.Map;

import synapticloop.linode.LinodeRequest;
import synapticloop.linode.exception.ApiException;

public class Domain {
	private static final String PARAM_CONSTANT_DOMAIN = "Domain";
	private static final String PARAM_CONSTANT_DESCRIPTION = "Description";
	private static final String PARAM_CONSTANT_TYPE = "Type";
	private static final String PARAM_CONSTANT_SOA_EMAIL = "SOA_Email";
	private static final String PARAM_CONSTANT_REFRESH_SEC = "Refresh_sec";
	private static final String PARAM_CONSTANT_RETRY_SEC = "Retry_sec";
	private static final String PARAM_CONSTANT_EXPIRE_SEC = "Expire_sec";
	private static final String PARAM_CONSTANT_TTL_SEC = "TTL_sec";
	private static final String PARAM_CONSTANT_LPM_DISPLAYGROUP = "lpm_displayGroup";
	private static final String PARAM_CONSTANT_STATUS = "status";
	private static final String PARAM_CONSTANT_MASTER_IPS = "master_ips";
	private static final String PARAM_CONSTANT_AXFR_IPS = "axfr_ips";
	private static final String PARAM_CONSTANT_DOMAINID = "DomainID";
	private static final String PARAM_CONSTANT_NAME = "Name";
	private static final String PARAM_CONSTANT_TARGET = "Target";
	private static final String PARAM_CONSTANT_PRIORITY = "Priority";
	private static final String PARAM_CONSTANT_WEIGHT = "Weight";
	private static final String PARAM_CONSTANT_PORT = "Port";
	private static final String PARAM_CONSTANT_PROTOCOL = "Protocol";
	private static final String PARAM_CONSTANT_RESOURCEID = "ResourceID";

	/**
	 * <p>Create a domain record.</p> 
	 * 
	 * Example response:
	 * 
	 * <pre>
	 * {
	 *    "ERRORARRAY":[],
	 *    "ACTION":"domain.create",
	 *    "DATA":{
	 *       "DomainID":5123
	 *    }
	 * }
	 * </pre>
	 * 
	 * Possible return error codes:
	 * 
	 *   - NOACCESS
	 *   - VALIDATION
	 *
	 * @param domain The zone's name
	 * @param type master or slave
	 *
	 * @return the linode request object
	 *
	 * @throws ApiException if a required parameter is null
	 */

	public static LinodeRequest create(String domain, String type) throws ApiException {
		Map<String, String> parameters = new HashMap<String, String>();
		if(null != domain) {
			parameters.put(PARAM_CONSTANT_DOMAIN, domain.toString());
		} else {
			throw new ApiException("Parameter 'domain' is required and cannot be null.");
		}
		if(null != type) {
			parameters.put(PARAM_CONSTANT_TYPE, type.toString());
		} else {
			throw new ApiException("Parameter 'type' is required and cannot be null.");
		}
		return(new LinodeRequest("domain.create", parameters));
	}

	/**
	 * <p>Create a domain record.</p> 
	 * 
	 * Example response:
	 * 
	 * <pre>
	 * {
	 *    "ERRORARRAY":[],
	 *    "ACTION":"domain.create",
	 *    "DATA":{
	 *       "DomainID":5123
	 *    }
	 * }
	 * </pre>
	 * 
	 * Possible return error codes:
	 * 
	 *   - NOACCESS
	 *   - VALIDATION
	 *
	 * @param domain The zone's name
	 * @param description Currently undisplayed.
	 * @param type master or slave
	 * @param SOA_Email Required when type=master
	 * @param Refresh_sec (<strong>SORRY</strong> there was no description provided for this parameter in the documentation, thereore I could not generate one)
	 * @param Retry_sec (<strong>SORRY</strong> there was no description provided for this parameter in the documentation, thereore I could not generate one)
	 * @param Expire_sec (<strong>SORRY</strong> there was no description provided for this parameter in the documentation, thereore I could not generate one)
	 * @param TTL_sec (<strong>SORRY</strong> there was no description provided for this parameter in the documentation, thereore I could not generate one)
	 * @param lpm_displayGroup Display group in the Domain list inside the Linode DNS Manager
	 * @param status 0, 1, or 2 (disabled, active, edit mode)
	 * @param master_ips When type=slave, the zone's master DNS servers list, semicolon separated 
	 * @param axfr_ips IP addresses allowed to AXFR the entire zone, semicolon separated
	 *
	 * @return the linode request object
	 *
	 * @throws ApiException if a required parameter is null
	 */

	public static LinodeRequest create(String domain, String description, String type, String SOA_Email, Long Refresh_sec, Long Retry_sec, Long Expire_sec, Long TTL_sec, String lpm_displayGroup, Long status, String master_ips, String axfr_ips) throws ApiException {
		Map<String, String> parameters = new HashMap<String, String>();
		if(null != domain) {
			parameters.put(PARAM_CONSTANT_DOMAIN, domain.toString());
		} else {
			throw new ApiException("Parameter 'domain' is required and cannot be null.");
		}
		if(null != description) {
			parameters.put(PARAM_CONSTANT_DESCRIPTION, description.toString());
		}
		if(null != type) {
			parameters.put(PARAM_CONSTANT_TYPE, type.toString());
		} else {
			throw new ApiException("Parameter 'type' is required and cannot be null.");
		}
		if(null != SOA_Email) {
			parameters.put(PARAM_CONSTANT_SOA_EMAIL, SOA_Email.toString());
		}
		if(null != Refresh_sec) {
			parameters.put(PARAM_CONSTANT_REFRESH_SEC, Refresh_sec.toString());
		}
		if(null != Retry_sec) {
			parameters.put(PARAM_CONSTANT_RETRY_SEC, Retry_sec.toString());
		}
		if(null != Expire_sec) {
			parameters.put(PARAM_CONSTANT_EXPIRE_SEC, Expire_sec.toString());
		}
		if(null != TTL_sec) {
			parameters.put(PARAM_CONSTANT_TTL_SEC, TTL_sec.toString());
		}
		if(null != lpm_displayGroup) {
			parameters.put(PARAM_CONSTANT_LPM_DISPLAYGROUP, lpm_displayGroup.toString());
		}
		if(null != status) {
			parameters.put(PARAM_CONSTANT_STATUS, status.toString());
		}
		if(null != master_ips) {
			parameters.put(PARAM_CONSTANT_MASTER_IPS, master_ips.toString());
		}
		if(null != axfr_ips) {
			parameters.put(PARAM_CONSTANT_AXFR_IPS, axfr_ips.toString());
		}
		return(new LinodeRequest("domain.create", parameters));
	}

	/**
	 * 
	 * Example response:
	 * 
	 * <pre>
	 * {
	 *    "ERRORARRAY":[],
	 *    "ACTION":"domain.delete",
	 *    "DATA":{
	 *       "DomainID":5123
	 *    }
	 * }
	 * </pre>
	 * 
	 * Possible return error codes:
	 * 
	 *   - NOTFOUND
	 *
	 * @param domainID (<strong>SORRY</strong> there was no description provided for this parameter in the documentation, thereore I could not generate one)
	 *
	 * @return the linode request object
	 *
	 * @throws ApiException if a required parameter is null
	 */

	public static LinodeRequest delete(Long domainID) throws ApiException {
		Map<String, String> parameters = new HashMap<String, String>();
		if(null != domainID) {
			parameters.put(PARAM_CONSTANT_DOMAINID, domainID.toString());
		} else {
			throw new ApiException("Parameter 'domainID' is required and cannot be null.");
		}
		return(new LinodeRequest("domain.delete", parameters));
	}

	/**
	 * <p>Lists domains you have access to.</p> 
	 * 
	 * Example response:
	 * 
	 * <pre>
	 * {
	 *    "ERRORARRAY":[],
	 *    "ACTION":"domain.list",
	 *    "DATA":[
	 *       {
	 *          "DOMAINID":5093,
	 *          "DESCRIPTION":"",
	 *          "TYPE":"master",
	 *          "STATUS":1,
	 *          "SOA_EMAIL":"dns@example.com",
	 *          "DOMAIN":"linode.com",
	 *          "RETRY_SEC":0,
	 *          "MASTER_IPS":"",
	 *          "EXPIRE_SEC":0,
	 *          "REFRESH_SEC":0,
	 *          "TTL_SEC":0
	 *       },
	 *       {
	 *          "DOMAINID":5125,
	 *          "DESCRIPTION":"",
	 *          "TYPE":"slave",
	 *          "STATUS":1,
	 *          "SOA_EMAIL":"",
	 *          "DOMAIN":"nodefs.com",
	 *          "RETRY_SEC":0,
	 *          "MASTER_IPS":"1.3.5.7;2.4.6.8;",
	 *          "EXPIRE_SEC":0,
	 *          "REFRESH_SEC":0,
	 *          "TTL_SEC":0
	 *       }
	 *    ]
	 * }
	 * </pre>
	 *
	 *
	 * @return the linode request object
	 *
	 * @throws ApiException if a required parameter is null
	 */

	public static LinodeRequest list() throws ApiException {
		Map<String, String> parameters = new HashMap<String, String>();
		return(new LinodeRequest("domain.list", parameters));
	}

	/**
	 * <p>Lists domains you have access to.</p> 
	 * 
	 * Example response:
	 * 
	 * <pre>
	 * {
	 *    "ERRORARRAY":[],
	 *    "ACTION":"domain.list",
	 *    "DATA":[
	 *       {
	 *          "DOMAINID":5093,
	 *          "DESCRIPTION":"",
	 *          "TYPE":"master",
	 *          "STATUS":1,
	 *          "SOA_EMAIL":"dns@example.com",
	 *          "DOMAIN":"linode.com",
	 *          "RETRY_SEC":0,
	 *          "MASTER_IPS":"",
	 *          "EXPIRE_SEC":0,
	 *          "REFRESH_SEC":0,
	 *          "TTL_SEC":0
	 *       },
	 *       {
	 *          "DOMAINID":5125,
	 *          "DESCRIPTION":"",
	 *          "TYPE":"slave",
	 *          "STATUS":1,
	 *          "SOA_EMAIL":"",
	 *          "DOMAIN":"nodefs.com",
	 *          "RETRY_SEC":0,
	 *          "MASTER_IPS":"1.3.5.7;2.4.6.8;",
	 *          "EXPIRE_SEC":0,
	 *          "REFRESH_SEC":0,
	 *          "TTL_SEC":0
	 *       }
	 *    ]
	 * }
	 * </pre>
	 *
	 * @param domainID Limits the list to the specified DomainID
	 *
	 * @return the linode request object
	 *
	 * @throws ApiException if a required parameter is null
	 */

	public static LinodeRequest list(Long domainID) throws ApiException {
		Map<String, String> parameters = new HashMap<String, String>();
		if(null != domainID) {
			parameters.put(PARAM_CONSTANT_DOMAINID, domainID.toString());
		}
		return(new LinodeRequest("domain.list", parameters));
	}

	/**
	 * <p>Create a domain record.</p> 
	 * 
	 * Example response:
	 * 
	 * <pre>
	 * {
	 *    "ERRORARRAY":[],
	 *    "ACTION":"domain.resource.create",
	 *    "DATA":{
	 *       "ResourceID":28537
	 *    }
	 * }
	 * </pre>
	 * 
	 * Possible return error codes:
	 * 
	 *   - NOACCESS
	 *   - VALIDATION
	 *
	 * @param domainID (<strong>SORRY</strong> there was no description provided for this parameter in the documentation, thereore I could not generate one)
	 * @param type One of: NS, MX, A, AAAA, CNAME, TXT, or SRV
	 *
	 * @return the linode request object
	 *
	 * @throws ApiException if a required parameter is null
	 */

	public static LinodeRequest resourcecreate(Long domainID, String type) throws ApiException {
		Map<String, String> parameters = new HashMap<String, String>();
		if(null != domainID) {
			parameters.put(PARAM_CONSTANT_DOMAINID, domainID.toString());
		} else {
			throw new ApiException("Parameter 'domainID' is required and cannot be null.");
		}
		if(null != type) {
			parameters.put(PARAM_CONSTANT_TYPE, type.toString());
		} else {
			throw new ApiException("Parameter 'type' is required and cannot be null.");
		}
		return(new LinodeRequest("domain.resource.create", parameters));
	}

	/**
	 * <p>Create a domain record.</p> 
	 * 
	 * Example response:
	 * 
	 * <pre>
	 * {
	 *    "ERRORARRAY":[],
	 *    "ACTION":"domain.resource.create",
	 *    "DATA":{
	 *       "ResourceID":28537
	 *    }
	 * }
	 * </pre>
	 * 
	 * Possible return error codes:
	 * 
	 *   - NOACCESS
	 *   - VALIDATION
	 *
	 * @param domainID (<strong>SORRY</strong> there was no description provided for this parameter in the documentation, thereore I could not generate one)
	 * @param type One of: NS, MX, A, AAAA, CNAME, TXT, or SRV
	 * @param name The hostname or FQDN. When Type=MX the subdomain to delegate to the Target MX server.
	 * @param target When Type=MX the hostname. When Type=CNAME the target of the alias. When Type=TXT the value of the record. When Type=A or AAAA the token of '[remote_addr]' will be substituted with the IP address of the request.
	 * @param priority Priority for MX and SRV records, 0-255
	 * @param weight (<strong>SORRY</strong> there was no description provided for this parameter in the documentation, thereore I could not generate one)
	 * @param port (<strong>SORRY</strong> there was no description provided for this parameter in the documentation, thereore I could not generate one)
	 * @param protocol The protocol to append to an SRV record. Ignored on other record types.
	 * @param TTL_sec TTL. Leave as 0 to accept our default.
	 *
	 * @return the linode request object
	 *
	 * @throws ApiException if a required parameter is null
	 */

	public static LinodeRequest resourcecreate(Long domainID, String type, String name, String target, Long priority, Long weight, Long port, String protocol, Long TTL_sec) throws ApiException {
		Map<String, String> parameters = new HashMap<String, String>();
		if(null != domainID) {
			parameters.put(PARAM_CONSTANT_DOMAINID, domainID.toString());
		} else {
			throw new ApiException("Parameter 'domainID' is required and cannot be null.");
		}
		if(null != type) {
			parameters.put(PARAM_CONSTANT_TYPE, type.toString());
		} else {
			throw new ApiException("Parameter 'type' is required and cannot be null.");
		}
		if(null != name) {
			parameters.put(PARAM_CONSTANT_NAME, name.toString());
		}
		if(null != target) {
			parameters.put(PARAM_CONSTANT_TARGET, target.toString());
		}
		if(null != priority) {
			parameters.put(PARAM_CONSTANT_PRIORITY, priority.toString());
		}
		if(null != weight) {
			parameters.put(PARAM_CONSTANT_WEIGHT, weight.toString());
		}
		if(null != port) {
			parameters.put(PARAM_CONSTANT_PORT, port.toString());
		}
		if(null != protocol) {
			parameters.put(PARAM_CONSTANT_PROTOCOL, protocol.toString());
		}
		if(null != TTL_sec) {
			parameters.put(PARAM_CONSTANT_TTL_SEC, TTL_sec.toString());
		}
		return(new LinodeRequest("domain.resource.create", parameters));
	}

	/**
	 * 
	 * Example response:
	 * 
	 * <pre>
	 * {
	 *    "ERRORARRAY":[],
	 *    "ACTION":"domain.resource.delete",
	 *    "DATA":{
	 *       "ResourceID":28537
	 *    }
	 * }
	 * </pre>
	 * 
	 * Possible return error codes:
	 * 
	 *   - NOTFOUND
	 *
	 * @param domainID (<strong>SORRY</strong> there was no description provided for this parameter in the documentation, thereore I could not generate one)
	 * @param resourceID (<strong>SORRY</strong> there was no description provided for this parameter in the documentation, thereore I could not generate one)
	 *
	 * @return the linode request object
	 *
	 * @throws ApiException if a required parameter is null
	 */

	public static LinodeRequest resourcedelete(Long domainID, Long resourceID) throws ApiException {
		Map<String, String> parameters = new HashMap<String, String>();
		if(null != domainID) {
			parameters.put(PARAM_CONSTANT_DOMAINID, domainID.toString());
		} else {
			throw new ApiException("Parameter 'domainID' is required and cannot be null.");
		}
		if(null != resourceID) {
			parameters.put(PARAM_CONSTANT_RESOURCEID, resourceID.toString());
		} else {
			throw new ApiException("Parameter 'resourceID' is required and cannot be null.");
		}
		return(new LinodeRequest("domain.resource.delete", parameters));
	}

	/**
	 * 
	 * Example response:
	 * 
	 * <pre>
	 * {
	 *    "ERRORARRAY":[],
	 *    "ACTION":"domain.resource.list",
	 *    "DATA":[
	 *       {
	 *          "PROTOCOL":"",
	 *          "TTL_SEC":0,
	 *          "PRIORITY":0,
	 *          "TYPE":"A",
	 *          "TARGET":"75.127.96.245",
	 *          "WEIGHT":0,
	 *          "RESOURCEID":28536,
	 *          "PORT":0,
	 *          "DOMAINID":5093,
	 *          "NAME":"www"
	 *       },
	 *       {
	 *          "PROTOCOL":"",
	 *          "TTL_SEC":0,
	 *          "PRIORITY":0,
	 *          "TYPE":"A",
	 *          "TARGET":"75.127.96.245",
	 *          "WEIGHT":0,
	 *          "RESOURCEID":28537,
	 *          "PORT":0,
	 *          "DOMAINID":5093,
	 *          "NAME":"mail"
	 *       }
	 *    ]
	 * }
	 * </pre>
	 *
	 * @param domainID (<strong>SORRY</strong> there was no description provided for this parameter in the documentation, thereore I could not generate one)
	 *
	 * @return the linode request object
	 *
	 * @throws ApiException if a required parameter is null
	 */

	public static LinodeRequest resourcelist(Long domainID) throws ApiException {
		Map<String, String> parameters = new HashMap<String, String>();
		if(null != domainID) {
			parameters.put(PARAM_CONSTANT_DOMAINID, domainID.toString());
		} else {
			throw new ApiException("Parameter 'domainID' is required and cannot be null.");
		}
		return(new LinodeRequest("domain.resource.list", parameters));
	}

	/**
	 * 
	 * Example response:
	 * 
	 * <pre>
	 * {
	 *    "ERRORARRAY":[],
	 *    "ACTION":"domain.resource.list",
	 *    "DATA":[
	 *       {
	 *          "PROTOCOL":"",
	 *          "TTL_SEC":0,
	 *          "PRIORITY":0,
	 *          "TYPE":"A",
	 *          "TARGET":"75.127.96.245",
	 *          "WEIGHT":0,
	 *          "RESOURCEID":28536,
	 *          "PORT":0,
	 *          "DOMAINID":5093,
	 *          "NAME":"www"
	 *       },
	 *       {
	 *          "PROTOCOL":"",
	 *          "TTL_SEC":0,
	 *          "PRIORITY":0,
	 *          "TYPE":"A",
	 *          "TARGET":"75.127.96.245",
	 *          "WEIGHT":0,
	 *          "RESOURCEID":28537,
	 *          "PORT":0,
	 *          "DOMAINID":5093,
	 *          "NAME":"mail"
	 *       }
	 *    ]
	 * }
	 * </pre>
	 *
	 * @param domainID (<strong>SORRY</strong> there was no description provided for this parameter in the documentation, thereore I could not generate one)
	 * @param resourceID (<strong>SORRY</strong> there was no description provided for this parameter in the documentation, thereore I could not generate one)
	 *
	 * @return the linode request object
	 *
	 * @throws ApiException if a required parameter is null
	 */

	public static LinodeRequest resourcelist(Long domainID, Long resourceID) throws ApiException {
		Map<String, String> parameters = new HashMap<String, String>();
		if(null != domainID) {
			parameters.put(PARAM_CONSTANT_DOMAINID, domainID.toString());
		} else {
			throw new ApiException("Parameter 'domainID' is required and cannot be null.");
		}
		if(null != resourceID) {
			parameters.put(PARAM_CONSTANT_RESOURCEID, resourceID.toString());
		}
		return(new LinodeRequest("domain.resource.list", parameters));
	}

	/**
	 * <p>Update a domain record.</p> 
	 * 
	 * Example response:
	 * 
	 * <pre>
	 * {
	 *    "ERRORARRAY":[],
	 *    "ACTION":"domain.resource.update",
	 *    "DATA":{
	 *       "ResourceID":28537
	 *    }
	 * }
	 * </pre>
	 * 
	 * Possible return error codes:
	 * 
	 *   - NOTFOUND
	 *   - VALIDATION
	 *
	 * @param resourceID (<strong>SORRY</strong> there was no description provided for this parameter in the documentation, thereore I could not generate one)
	 *
	 * @return the linode request object
	 *
	 * @throws ApiException if a required parameter is null
	 */

	public static LinodeRequest resourceupdate(Long resourceID) throws ApiException {
		Map<String, String> parameters = new HashMap<String, String>();
		if(null != resourceID) {
			parameters.put(PARAM_CONSTANT_RESOURCEID, resourceID.toString());
		} else {
			throw new ApiException("Parameter 'resourceID' is required and cannot be null.");
		}
		return(new LinodeRequest("domain.resource.update", parameters));
	}

	/**
	 * <p>Update a domain record.</p> 
	 * 
	 * Example response:
	 * 
	 * <pre>
	 * {
	 *    "ERRORARRAY":[],
	 *    "ACTION":"domain.resource.update",
	 *    "DATA":{
	 *       "ResourceID":28537
	 *    }
	 * }
	 * </pre>
	 * 
	 * Possible return error codes:
	 * 
	 *   - NOTFOUND
	 *   - VALIDATION
	 *
	 * @param domainID (<strong>SORRY</strong> there was no description provided for this parameter in the documentation, thereore I could not generate one)
	 * @param resourceID (<strong>SORRY</strong> there was no description provided for this parameter in the documentation, thereore I could not generate one)
	 * @param name The hostname or FQDN. When Type=MX the subdomain to delegate to the Target MX server.
	 * @param target When Type=MX the hostname. When Type=CNAME the target of the alias. When Type=TXT the value of the record. When Type=A or AAAA the token of '[remote_addr]' will be substituted with the IP address of the request.
	 * @param priority Priority for MX and SRV records, 0-255
	 * @param weight (<strong>SORRY</strong> there was no description provided for this parameter in the documentation, thereore I could not generate one)
	 * @param port (<strong>SORRY</strong> there was no description provided for this parameter in the documentation, thereore I could not generate one)
	 * @param protocol The protocol to append to an SRV record. Ignored on other record types.
	 * @param TTL_sec TTL. Leave as 0 to accept our default.
	 *
	 * @return the linode request object
	 *
	 * @throws ApiException if a required parameter is null
	 */

	public static LinodeRequest resourceupdate(Long domainID, Long resourceID, String name, String target, Long priority, Long weight, Long port, String protocol, Long TTL_sec) throws ApiException {
		Map<String, String> parameters = new HashMap<String, String>();
		if(null != domainID) {
			parameters.put(PARAM_CONSTANT_DOMAINID, domainID.toString());
		}
		if(null != resourceID) {
			parameters.put(PARAM_CONSTANT_RESOURCEID, resourceID.toString());
		} else {
			throw new ApiException("Parameter 'resourceID' is required and cannot be null.");
		}
		if(null != name) {
			parameters.put(PARAM_CONSTANT_NAME, name.toString());
		}
		if(null != target) {
			parameters.put(PARAM_CONSTANT_TARGET, target.toString());
		}
		if(null != priority) {
			parameters.put(PARAM_CONSTANT_PRIORITY, priority.toString());
		}
		if(null != weight) {
			parameters.put(PARAM_CONSTANT_WEIGHT, weight.toString());
		}
		if(null != port) {
			parameters.put(PARAM_CONSTANT_PORT, port.toString());
		}
		if(null != protocol) {
			parameters.put(PARAM_CONSTANT_PROTOCOL, protocol.toString());
		}
		if(null != TTL_sec) {
			parameters.put(PARAM_CONSTANT_TTL_SEC, TTL_sec.toString());
		}
		return(new LinodeRequest("domain.resource.update", parameters));
	}

	/**
	 * <p>Update a domain record.</p> 
	 * 
	 * Example response:
	 * 
	 * <pre>
	 * {
	 *    "ERRORARRAY":[],
	 *    "ACTION":"domain.update",
	 *    "DATA":{
	 *       "DomainID":5123
	 *    }
	 * }
	 * </pre>
	 * 
	 * Possible return error codes:
	 * 
	 *   - NOTFOUND
	 *   - VALIDATION
	 *
	 * @param domainID (<strong>SORRY</strong> there was no description provided for this parameter in the documentation, thereore I could not generate one)
	 *
	 * @return the linode request object
	 *
	 * @throws ApiException if a required parameter is null
	 */

	public static LinodeRequest update(Long domainID) throws ApiException {
		Map<String, String> parameters = new HashMap<String, String>();
		if(null != domainID) {
			parameters.put(PARAM_CONSTANT_DOMAINID, domainID.toString());
		} else {
			throw new ApiException("Parameter 'domainID' is required and cannot be null.");
		}
		return(new LinodeRequest("domain.update", parameters));
	}

	/**
	 * <p>Update a domain record.</p> 
	 * 
	 * Example response:
	 * 
	 * <pre>
	 * {
	 *    "ERRORARRAY":[],
	 *    "ACTION":"domain.update",
	 *    "DATA":{
	 *       "DomainID":5123
	 *    }
	 * }
	 * </pre>
	 * 
	 * Possible return error codes:
	 * 
	 *   - NOTFOUND
	 *   - VALIDATION
	 *
	 * @param domainID (<strong>SORRY</strong> there was no description provided for this parameter in the documentation, thereore I could not generate one)
	 * @param domain The zone's name
	 * @param description Currently undisplayed.
	 * @param type master or slave
	 * @param SOA_Email Required when type=master
	 * @param Refresh_sec (<strong>SORRY</strong> there was no description provided for this parameter in the documentation, thereore I could not generate one)
	 * @param Retry_sec (<strong>SORRY</strong> there was no description provided for this parameter in the documentation, thereore I could not generate one)
	 * @param Expire_sec (<strong>SORRY</strong> there was no description provided for this parameter in the documentation, thereore I could not generate one)
	 * @param TTL_sec (<strong>SORRY</strong> there was no description provided for this parameter in the documentation, thereore I could not generate one)
	 * @param lpm_displayGroup Display group in the Domain list inside the Linode DNS Manager
	 * @param status 0, 1, or 2 (disabled, active, edit mode)
	 * @param master_ips When type=slave, the zone's master DNS servers list, semicolon separated 
	 * @param axfr_ips IP addresses allowed to AXFR the entire zone, semicolon separated
	 *
	 * @return the linode request object
	 *
	 * @throws ApiException if a required parameter is null
	 */

	public static LinodeRequest update(Long domainID, String domain, String description, String type, String SOA_Email, Long Refresh_sec, Long Retry_sec, Long Expire_sec, Long TTL_sec, String lpm_displayGroup, Long status, String master_ips, String axfr_ips) throws ApiException {
		Map<String, String> parameters = new HashMap<String, String>();
		if(null != domainID) {
			parameters.put(PARAM_CONSTANT_DOMAINID, domainID.toString());
		} else {
			throw new ApiException("Parameter 'domainID' is required and cannot be null.");
		}
		if(null != domain) {
			parameters.put(PARAM_CONSTANT_DOMAIN, domain.toString());
		}
		if(null != description) {
			parameters.put(PARAM_CONSTANT_DESCRIPTION, description.toString());
		}
		if(null != type) {
			parameters.put(PARAM_CONSTANT_TYPE, type.toString());
		}
		if(null != SOA_Email) {
			parameters.put(PARAM_CONSTANT_SOA_EMAIL, SOA_Email.toString());
		}
		if(null != Refresh_sec) {
			parameters.put(PARAM_CONSTANT_REFRESH_SEC, Refresh_sec.toString());
		}
		if(null != Retry_sec) {
			parameters.put(PARAM_CONSTANT_RETRY_SEC, Retry_sec.toString());
		}
		if(null != Expire_sec) {
			parameters.put(PARAM_CONSTANT_EXPIRE_SEC, Expire_sec.toString());
		}
		if(null != TTL_sec) {
			parameters.put(PARAM_CONSTANT_TTL_SEC, TTL_sec.toString());
		}
		if(null != lpm_displayGroup) {
			parameters.put(PARAM_CONSTANT_LPM_DISPLAYGROUP, lpm_displayGroup.toString());
		}
		if(null != status) {
			parameters.put(PARAM_CONSTANT_STATUS, status.toString());
		}
		if(null != master_ips) {
			parameters.put(PARAM_CONSTANT_MASTER_IPS, master_ips.toString());
		}
		if(null != axfr_ips) {
			parameters.put(PARAM_CONSTANT_AXFR_IPS, axfr_ips.toString());
		}
		return(new LinodeRequest("domain.update", parameters));
	}

};