package synapticloop.linode.api;

// - - - - thoughtfully generated by synapticloop linode-api - - - - 
//     with the use of synapticloop templar templating language
//               (java-create-api.templar)

import java.util.HashMap;
import java.util.Map;

import synapticloop.linode.LinodeRequest;
import synapticloop.linode.exception.ApiException;

/**
 * This is the interaction class for the Stackscript api calls, this was automatically
 * generated from the linode api documentation.
 * 
 * @author synapticloop
 */

public class Stackscript {
	private static final String PARAM_CONSTANT_LABEL = "Label";
	private static final String PARAM_CONSTANT_DESCRIPTION = "Description";
	private static final String PARAM_CONSTANT_DISTRIBUTIONIDLIST = "DistributionIDList";
	private static final String PARAM_CONSTANT_ISPUBLIC = "isPublic";
	private static final String PARAM_CONSTANT_REV_NOTE = "rev_note";
	private static final String PARAM_CONSTANT_SCRIPT = "script";
	private static final String PARAM_CONSTANT_STACKSCRIPTID = "StackScriptID";

/**
 * Private constructor to deter instantiation
 */
private Stackscript() {}

	/**
	 * <p>Create a StackScript.</p> 
	 * 
	 * Example response:
	 * 
	 * <pre>
	 * {
	 *    ERRORARRAY: [ ],
	 *    DATA: {
	 *       StackScriptID: 3
	 *    },
	 *    ACTION: "stackscript.create"
	 * }
	 * </pre>
	 * 
	 * Possible return error codes:
	 * 
	 *   - NOACCESS
	 *   - VALIDATION
	 *
	 * @param label The Label for this StackScript
	 * @param distributionIDList Comma delimited list of DistributionIDs that this script works on 
	 * @param script The actual script
	 *
	 * @return the linode request object
	 *
	 * @throws ApiException if a required parameter is null
	 */

	public static LinodeRequest create(String label, String distributionIDList, String script) throws ApiException {
		Map<String, String> parameters = new HashMap<String, String>();
		if(null != label) {
			parameters.put(PARAM_CONSTANT_LABEL, label.toString());
		} else {
			throw new ApiException("Parameter 'label' is required and cannot be null.");
		}
		if(null != distributionIDList) {
			parameters.put(PARAM_CONSTANT_DISTRIBUTIONIDLIST, distributionIDList.toString());
		} else {
			throw new ApiException("Parameter 'distributionIDList' is required and cannot be null.");
		}
		if(null != script) {
			parameters.put(PARAM_CONSTANT_SCRIPT, script.toString());
		} else {
			throw new ApiException("Parameter 'script' is required and cannot be null.");
		}
		return(new LinodeRequest("stackscript.create", parameters));
	}

	/**
	 * <p>Create a StackScript.</p> 
	 * 
	 * Example response:
	 * 
	 * <pre>
	 * {
	 *    ERRORARRAY: [ ],
	 *    DATA: {
	 *       StackScriptID: 3
	 *    },
	 *    ACTION: "stackscript.create"
	 * }
	 * </pre>
	 * 
	 * Possible return error codes:
	 * 
	 *   - NOACCESS
	 *   - VALIDATION
	 *
	 * @param label The Label for this StackScript
	 * @param description (<strong>SORRY</strong> there was no description provided for this parameter in the documentation, thereore I could not generate one)
	 * @param distributionIDList Comma delimited list of DistributionIDs that this script works on 
	 * @param isPublic Whether this StackScript is published in the Library, for everyone to use
	 * @param rev_note (<strong>SORRY</strong> there was no description provided for this parameter in the documentation, thereore I could not generate one)
	 * @param script The actual script
	 *
	 * @return the linode request object
	 *
	 * @throws ApiException if a required parameter is null
	 */

	public static LinodeRequest create(String label, String description, String distributionIDList, Boolean isPublic, String rev_note, String script) throws ApiException {
		Map<String, String> parameters = new HashMap<String, String>();
		if(null != label) {
			parameters.put(PARAM_CONSTANT_LABEL, label.toString());
		} else {
			throw new ApiException("Parameter 'label' is required and cannot be null.");
		}
		if(null != description) {
			parameters.put(PARAM_CONSTANT_DESCRIPTION, description.toString());
		}
		if(null != distributionIDList) {
			parameters.put(PARAM_CONSTANT_DISTRIBUTIONIDLIST, distributionIDList.toString());
		} else {
			throw new ApiException("Parameter 'distributionIDList' is required and cannot be null.");
		}
		if(null != isPublic) {
			parameters.put(PARAM_CONSTANT_ISPUBLIC, isPublic.toString());
		}
		if(null != rev_note) {
			parameters.put(PARAM_CONSTANT_REV_NOTE, rev_note.toString());
		}
		if(null != script) {
			parameters.put(PARAM_CONSTANT_SCRIPT, script.toString());
		} else {
			throw new ApiException("Parameter 'script' is required and cannot be null.");
		}
		return(new LinodeRequest("stackscript.create", parameters));
	}

	/**
	 * 
	 * Example response:
	 * 
	 * <pre>
	 * {
	 *    ERRORARRAY: [ ],
	 *    DATA: {
	 *       StackScriptID: 3
	 *    },
	 *    ACTION: "stackscript.delete"
	 * }
	 * </pre>
	 * 
	 * Possible return error codes:
	 * 
	 *   - NOTFOUND
	 *
	 * @param stackScriptID (<strong>SORRY</strong> there was no description provided for this parameter in the documentation, thereore I could not generate one)
	 *
	 * @return the linode request object
	 *
	 * @throws ApiException if a required parameter is null
	 */

	public static LinodeRequest delete(Long stackScriptID) throws ApiException {
		Map<String, String> parameters = new HashMap<String, String>();
		if(null != stackScriptID) {
			parameters.put(PARAM_CONSTANT_STACKSCRIPTID, stackScriptID.toString());
		} else {
			throw new ApiException("Parameter 'stackScriptID' is required and cannot be null.");
		}
		return(new LinodeRequest("stackscript.delete", parameters));
	}

	/**
	 * <p>Lists StackScripts you have access to.</p> 
	 * 
	 * Example response:
	 * 
	 * <pre>
	 * {
	 *    ERRORARRAY: [ ],
	 *    DATA: [
	 *       {
	 *          SCRIPT: "#!/bin/bash
	 *                   # this is the content of the first StackScript",
	 *          DESCRIPTION: "",
	 *          DISTRIBUTIONIDLIST: "77,78",
	 *          LABEL: "StackScript001",
	 *          DEPLOYMENTSTOTAL: 1,
	 *          LATESTREV: 1,
	 *          CREATE_DT: "2012-05-22 16:35:42.0",
	 *          DEPLOYMENTSACTIVE: 1,
	 *          STACKSCRIPTID: 1,
	 *          REV_NOTE: "Initial import",
	 *          REV_DT: "2012-05-22 16:35:42.0",
	 *          ISPUBLIC: 1,
	 *          USERID: 91886
	 *       },
	 *       {
	 *          SCRIPT: "#!/bin/bash
	 *                   # this is the content of the other script",
	 *          DESCRIPTION: "",
	 *          DISTRIBUTIONIDLIST: "77,78",
	 *          LABEL: "StackScript002",
	 *          DEPLOYMENTSTOTAL: 0,
	 *          LATESTREV: 2,
	 *          CREATE_DT: "2012-05-22 17:12:48.0",
	 *          DEPLOYMENTSACTIVE: 0,
	 *          STACKSCRIPTID: 2,
	 *          REV_NOTE: "Initial import",
	 *          REV_DT: "2012-05-22 17:12:48.0",
	 *          ISPUBLIC: 1,
	 *          USERID: 91886
	 *       }
	 *    ],
	 *    ACTION: "stackscript.list"
	 * }
	 * </pre>
	 *
	 *
	 * @return the linode request object
	 *
	 * @throws ApiException if a required parameter is null
	 */

	public static LinodeRequest list() throws ApiException {
		Map<String, String> parameters = new HashMap<String, String>();
		return(new LinodeRequest("stackscript.list", parameters));
	}

	/**
	 * <p>Lists StackScripts you have access to.</p> 
	 * 
	 * Example response:
	 * 
	 * <pre>
	 * {
	 *    ERRORARRAY: [ ],
	 *    DATA: [
	 *       {
	 *          SCRIPT: "#!/bin/bash
	 *                   # this is the content of the first StackScript",
	 *          DESCRIPTION: "",
	 *          DISTRIBUTIONIDLIST: "77,78",
	 *          LABEL: "StackScript001",
	 *          DEPLOYMENTSTOTAL: 1,
	 *          LATESTREV: 1,
	 *          CREATE_DT: "2012-05-22 16:35:42.0",
	 *          DEPLOYMENTSACTIVE: 1,
	 *          STACKSCRIPTID: 1,
	 *          REV_NOTE: "Initial import",
	 *          REV_DT: "2012-05-22 16:35:42.0",
	 *          ISPUBLIC: 1,
	 *          USERID: 91886
	 *       },
	 *       {
	 *          SCRIPT: "#!/bin/bash
	 *                   # this is the content of the other script",
	 *          DESCRIPTION: "",
	 *          DISTRIBUTIONIDLIST: "77,78",
	 *          LABEL: "StackScript002",
	 *          DEPLOYMENTSTOTAL: 0,
	 *          LATESTREV: 2,
	 *          CREATE_DT: "2012-05-22 17:12:48.0",
	 *          DEPLOYMENTSACTIVE: 0,
	 *          STACKSCRIPTID: 2,
	 *          REV_NOTE: "Initial import",
	 *          REV_DT: "2012-05-22 17:12:48.0",
	 *          ISPUBLIC: 1,
	 *          USERID: 91886
	 *       }
	 *    ],
	 *    ACTION: "stackscript.list"
	 * }
	 * </pre>
	 *
	 * @param stackScriptID Limits the list to the specified StackScriptID
	 *
	 * @return the linode request object
	 *
	 * @throws ApiException if a required parameter is null
	 */

	public static LinodeRequest list(Long stackScriptID) throws ApiException {
		Map<String, String> parameters = new HashMap<String, String>();
		if(null != stackScriptID) {
			parameters.put(PARAM_CONSTANT_STACKSCRIPTID, stackScriptID.toString());
		}
		return(new LinodeRequest("stackscript.list", parameters));
	}

	/**
	 * <p>Update a StackScript.</p> 
	 * 
	 * Example response:
	 * 
	 * <pre>
	 * {
	 *    ERRORARRAY: [ ],
	 *    DATA: {
	 *       StackScriptID: 3718
	 *    },
	 *    ACTION: "stackscript.update"
	 * }
	 * </pre>
	 * 
	 * Possible return error codes:
	 * 
	 *   - NOTFOUND
	 *   - VALIDATION
	 *
	 * @param stackScriptID (<strong>SORRY</strong> there was no description provided for this parameter in the documentation, thereore I could not generate one)
	 *
	 * @return the linode request object
	 *
	 * @throws ApiException if a required parameter is null
	 */

	public static LinodeRequest update(Long stackScriptID) throws ApiException {
		Map<String, String> parameters = new HashMap<String, String>();
		if(null != stackScriptID) {
			parameters.put(PARAM_CONSTANT_STACKSCRIPTID, stackScriptID.toString());
		} else {
			throw new ApiException("Parameter 'stackScriptID' is required and cannot be null.");
		}
		return(new LinodeRequest("stackscript.update", parameters));
	}

	/**
	 * <p>Update a StackScript.</p> 
	 * 
	 * Example response:
	 * 
	 * <pre>
	 * {
	 *    ERRORARRAY: [ ],
	 *    DATA: {
	 *       StackScriptID: 3718
	 *    },
	 *    ACTION: "stackscript.update"
	 * }
	 * </pre>
	 * 
	 * Possible return error codes:
	 * 
	 *   - NOTFOUND
	 *   - VALIDATION
	 *
	 * @param stackScriptID (<strong>SORRY</strong> there was no description provided for this parameter in the documentation, thereore I could not generate one)
	 * @param label The Label for this StackScript
	 * @param description (<strong>SORRY</strong> there was no description provided for this parameter in the documentation, thereore I could not generate one)
	 * @param distributionIDList Comma delimited list of DistributionIDs that this script works on 
	 * @param isPublic Whether this StackScript is published in the Library, for everyone to use
	 * @param rev_note (<strong>SORRY</strong> there was no description provided for this parameter in the documentation, thereore I could not generate one)
	 * @param script The actual script
	 *
	 * @return the linode request object
	 *
	 * @throws ApiException if a required parameter is null
	 */

	public static LinodeRequest update(Long stackScriptID, String label, String description, String distributionIDList, Boolean isPublic, String rev_note, String script) throws ApiException {
		Map<String, String> parameters = new HashMap<String, String>();
		if(null != stackScriptID) {
			parameters.put(PARAM_CONSTANT_STACKSCRIPTID, stackScriptID.toString());
		} else {
			throw new ApiException("Parameter 'stackScriptID' is required and cannot be null.");
		}
		if(null != label) {
			parameters.put(PARAM_CONSTANT_LABEL, label.toString());
		}
		if(null != description) {
			parameters.put(PARAM_CONSTANT_DESCRIPTION, description.toString());
		}
		if(null != distributionIDList) {
			parameters.put(PARAM_CONSTANT_DISTRIBUTIONIDLIST, distributionIDList.toString());
		}
		if(null != isPublic) {
			parameters.put(PARAM_CONSTANT_ISPUBLIC, isPublic.toString());
		}
		if(null != rev_note) {
			parameters.put(PARAM_CONSTANT_REV_NOTE, rev_note.toString());
		}
		if(null != script) {
			parameters.put(PARAM_CONSTANT_SCRIPT, script.toString());
		}
		return(new LinodeRequest("stackscript.update", parameters));
	}

};