package synapticloop.linode.api;

// - - - - thoughtfully generated by synapticloop linode-api - - - - 
//     with the use of synapticloop templar templating language
//               (java-create-api.templar)

import java.util.HashMap;
import java.util.Map;

import synapticloop.linode.LinodeRequest;
import synapticloop.linode.exception.ApiException;

public class Test {

	/**
	 * <p>Echos back parameters that were passed in.</p> 
	 * 
	 * Example response:
	 * 
	 * <pre>
	 * {
	 *    "ERRORARRAY":[],
	 *    "ACTION":"test.echo",
	 *    "DATA":{
	 *       "foo": "bar"
	 *    }
	 * }
	 * </pre>
	 *
	 *
	 * @throws ApiException if a required parameter is null
	 */

	public static LinodeRequest echo() throws ApiException {
		Map<String, String> parameters = new HashMap<String, String>();
		return(new LinodeRequest("test.echo", parameters));
	}

};